### ISSUE TITLE
Crashes on startup with --hyperion hyperion.conf.json

### ISSUE THREAD

**Issue by penfold42** [redPanther/hypersim#3]
C:\utils\hyperion\hypersim\src>\Python34\python.exe hypersim.py --hyperion hyperion.config.json.pwm-16x16
Traceback (most recent call last):
  File "hypersim.py", line 15, in <module>
    app = MainWindow(parent=root)
  File "C:\utils\hyperion\hypersim\src\mainwindow.py", line 48, in **init**
    self.loadConfig()
  File "C:\utils\hyperion\hypersim\src\mainwindow.py", line 79, in loadConfig
    self.resetUI()
  File "C:\utils\hyperion\hypersim\src\mainwindow.py", line 58, in resetUI
    self.opcServer.standby(True)
AttributeError: 'MainWindow' object has no attribute 'opcServer'

**Comment by redPanther** [comment]
can you 'pastebin' your config?

**Comment by penfold42** [comment]
Sorry, should have been more specific.
it works fine if I load it from the menu rather than command line.

This seems to have fixed it - just moving the OPCServer initialiser before the loadConfig

[diffs.txt](https://github.com/redPanther/hypersim/files/197357/diffs.txt)

**Comment by redPanther** [comment]
should by fixed

**Comment by penfold42** [comment]
Yep
